import { RendererFactory2, NgZone } from '@angular/core';
import { CookieService } from 'ngx-cookie';
import { PeAuthSubject } from '../declarations/index';
import { Observable } from 'rxjs';
import { PeAuthTypeFactory } from './pe-auth.type.factory';
import * as ɵngcc0 from '@angular/core';
export declare class PeAuthService {
    private peAuthTypeFactory;
    private cookieService;
    private rendererFactory;
    private ngZone;
    static readonly CXN_OFF: string;
    static readonly CXN_PROGRESS: string;
    static readonly CXN_ECHEC: string;
    static readonly CXN_MAX_RETRY: string;
    static readonly CXN_SUCCESS: string;
    private _time;
    private _type;
    private _mode;
    private _status;
    private _token;
    private _nbAttempt;
    private _subject;
    private _cookieOptions;
    private _authType;
    private _iframe;
    private _iframeLoadListener;
    private _windowMessageListener;
    private _renderer;
    private _onConnect;
    constructor(peAuthTypeFactory: PeAuthTypeFactory, cookieService: CookieService, rendererFactory: RendererFactory2, ngZone: NgZone);
    on(event: "connect", fn: (token: string, refreshToken: boolean, attempt: number) => Observable<boolean> | Promise<boolean> | boolean): void;
    private afterCxn(token, status, refreshToken);
    private isPromise(obj);
    private isObservable(obj);
    isConnected(): boolean;
    getStatus(): Observable<PeAuthSubject>;
    readonly status: string;
    readonly type: string;
    readonly mode: string;
    readonly authorizationHeader: string;
    readonly loginRoute: any[];
    private clear();
    logout(): Observable<PeAuthSubject>;
    private inProgress(refreshToken);
    connect(type: string, mode: string, container?: HTMLElement): Observable<PeAuthSubject>;
    refreshToken(container?: HTMLElement): Observable<PeAuthSubject>;
    private getIframeParentNode();
    private stopListening();
    private authByUrl(url);
    private recievedMessage;
    private iframeLoaded;
    private auth(container, refreshToken);
    private authByCookie();
    static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<PeAuthService, never>;
    static ɵprov: ɵngcc0.ɵɵInjectableDeclaration<PeAuthService>;
}

//# sourceMappingURL=pe-auth.service.d.ts.map